import type { Account, LoginResponse, Transaction, User } from '@/types'
const asR=(v:unknown)=>v!==null&&typeof v==='object'?v as Record<string,unknown>:{}
const pickS=(...a:unknown[])=>{for(const v of a){if(typeof v==='string'&&v.trim())return v.trim()}return''}
const pickN=(...a:unknown[])=>{for(const v of a){if(typeof v==='number'&&Number.isFinite(v))return v; if(typeof v==='string'){const n=Number(v.replace(/[^\d.-]/g,'')); if(Number.isFinite(n))return n}}return 0}
export const buildUserFromLogin=(r:LoginResponse):User=>{const roleRaw=pickS(r.role,'USER').toUpperCase();const role=roleRaw.startsWith('ROLE_')?roleRaw.slice(5):roleRaw;const local=r.email.split('@')[0]||'User';const fullName=local.split(/[._-]/).map(p=>p[0].toUpperCase()+p.slice(1)).join(' ');return {email:r.email,role,fullName,token:r.token}}
export const normalizeAccount=(i:unknown):Account=>{const x=asR(i);const now=new Date().toISOString();return{id:pickN(x.id),accountNumber:pickS(x.accountNumber,'N/A'),accountType:pickS(x.accountType,'SAVINGS').toUpperCase(),balance:pickN(x.balance),currency:pickS(x.currency,'IDR').toUpperCase(),status:pickS(x.status,'ACTIVE').toUpperCase(),customerId:pickN(x.customerId)||undefined,customerName:pickS(x.ownerName,x.customerName,'Account Owner'),customerEmail:pickS(x.ownerEmail,x.email)||undefined,interestRate:pickN(x.interestRate)||undefined,createdAt:pickS(x.createdAt,now),updatedAt:pickS(x.updatedAt,now)}}
export const normalizeTransaction=(i:unknown):Transaction=>{const r=asR(i);const type=pickS(r.type,'TRANSFER').toUpperCase();const id=pickN(r.id,Date.now());return{id,type,amount:pickN(r.amount),currency:pickS(r.currency,'IDR').toUpperCase(),description:pickS(r.description,`${type} transaction`),status:pickS(r.status,'COMPLETED').toUpperCase(),fromAccountId:pickN(r.fromAccountId)||undefined,fromAccountNumber:pickS(r.fromAccountNumber)||undefined,toAccountId:pickN(r.toAccountId)||undefined,toAccountNumber:pickS(r.toAccountNumber)||undefined,referenceNumber:pickS(r.referenceNumber,`TX-${id}`),createdAt:pickS(r.createdAt,new Date().toISOString()),completedAt:pickS(r.completedAt)||undefined,balanceAfter:pickN(r.balanceAfter)||undefined}}
export const decodeJwtPayload=(t:string)=>{try{const[,p]=t.split('.');if(!p)return null;return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/')))}catch{return null}}
export const isTokenExpired=(token:string)=>{const p=decodeJwtPayload(token) as any;const exp=typeof p?.exp==='number'?p.exp:null;return exp?exp*1000<=Date.now():false}
