import React from 'react'
import { ChevronLeft, ChevronRight, Inbox } from 'lucide-react'
interface Column<T>{ key:string; header:string; render:(item:T)=>React.ReactNode; className?:string }
interface Props<T>{ columns:Column<T>[]; data:T[]; isLoading?:boolean; emptyMessage?:string; currentPage?:number; totalPages?:number; onPageChange?:(p:number)=>void; onRowClick?:(item:T)=>void }
export function DataTable<T>({ columns, data, isLoading=false, emptyMessage='No data available', currentPage=0, totalPages=1, onPageChange, onRowClick }:Props<T>){
  if(isLoading){ return <div className="glass-panel overflow-hidden rounded-[36px]"><div className="animate-pulse"><div className="h-12 border-b border-navy-100 bg-navy-50/70" />{[...Array(5)].map((_,i)=><div key={i} className="flex h-16 items-center gap-6 border-b border-navy-50/70 px-6"><div className="h-3 w-1/4 rounded bg-navy-100" /><div className="h-3 w-1/3 rounded bg-navy-100" /><div className="h-3 w-1/6 rounded bg-navy-100" /><div className="ml-auto h-3 w-1/5 rounded bg-navy-100" /></div>)}</div></div> }
  if(!data.length){ return <div className="glass-panel rounded-[36px] py-10"><div className="flex flex-col items-center text-navy-400"><Inbox className="mb-3 h-12 w-12 text-navy-200" /><p className="text-base font-semibold text-charcoal">{emptyMessage}</p><p className="mt-1 text-sm text-navy-400">Try adjusting your filters</p></div></div> }
  return <div className="glass-panel overflow-hidden rounded-[36px]">
    <div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-navy-100 bg-navy-50/60">{columns.map(c=><th key={c.key} className={`px-5 py-4 text-left text-[11px] font-bold uppercase tracking-[0.18em] text-navy-500 ${c.className??''}`}>{c.header}</th>)}</tr></thead>
    <tbody className="divide-y divide-navy-50">{data.map((item, idx)=><tr key={idx} onClick={()=>onRowClick?.(item)} className={`transition-colors hover:bg-navy-50/40 ${onRowClick?'cursor-pointer':''}`}>{columns.map(col=><td key={col.key} className={`px-5 py-4 ${col.className??''}`}>{col.render(item)}</td>)}</tr>)}</tbody></table></div>
    {totalPages>1 && onPageChange && <div className="flex items-center justify-between border-t border-navy-100 bg-navy-50/30 px-5 py-3"><p className="text-xs font-medium text-navy-500">Page {currentPage+1} of {totalPages}</p><div className="flex items-center gap-1"><button onClick={()=>onPageChange(currentPage-1)} disabled={currentPage===0} className="flex h-9 w-9 items-center justify-center rounded-[18px] border border-line-soft disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><button onClick={()=>onPageChange(currentPage+1)} disabled={currentPage>=totalPages-1} className="flex h-9 w-9 items-center justify-center rounded-[18px] border border-line-soft disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div></div>}
  </div>
}
